on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - name: Test
      run: |
        go version
        go test -race ./...